#ifndef	_ERROR_H_
#define	_ERROR_H_

//#ifdef __cplusplus
//	extern "C" {
//#endif

enum{
	ERROR_NO = 0,
	ERROR_MODULE_BASE=256,
	ERROR_MODULE_SYSMON=ERROR_MODULE_BASE,			// 256
	ERROR_MODULE_EERPOM=(ERROR_MODULE_BASE+16),		// 272
	ERROR_MODULE_INA3221=(ERROR_MODULE_EERPOM+16),	// 288
	ERROR_MODULE_INA2xx=(ERROR_MODULE_INA3221+16),		// 304
	ERROR_MODULE_ADS7828=(ERROR_MODULE_INA2xx+16),	// 320
	ERROR_MODULE_TMP75=(ERROR_MODULE_ADS7828+16),		// 336
	ERROR_OTHERS,
};




//#ifdef __cplusplus
//	}
//#endif

#endif

